name: Auto Post Harian

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  autopost:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Jalankan script generate_artikel.py
        run: |
          python generate_artikel.py

      - name: Commit dan Push
        run: |
          git config user.name "rocket-auto"
          git config user.email "rocket@users.noreply.github.com"
          git add .
          git commit -m "Auto-post artikel harian `date`" || echo "No changes"
          git push
